"""remove is_active column

Revision ID: 01fd1c6beb79
Revises: 001
Create Date: 2026-09-05 22:10:04.360033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01fd1c6beb79'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
