"""add is_active back

Revision ID: 0897bfe3ad9a
Revises: 01fd1c6beb79
Create Date: 2026-09-05 22:12:56.843182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0897bfe3ad9a'
down_revision: Union[str, Sequence[str], None] = '01fd1c6beb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
